//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-11-28 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\João\\Documents\\GitHub\\mfes_stratego/Position.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Position implements EvaluatePP {

// ***** VDMTOOLS START Name=column KEEP=NO
  public volatile Number column = null;
// ***** VDMTOOLS END Name=column

// ***** VDMTOOLS START Name=row KEEP=NO
  public volatile Number row = null;
// ***** VDMTOOLS END Name=row

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=PositionSentinel KEEP=NO
  class PositionSentinel extends Sentinel {

    public final int Position = 0;

    public final int nr_functions = 1;


    public PositionSentinel () throws CGException {}


    public PositionSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=PositionSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new PositionSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_Position KEEP=NO
  private void vdm_init_Position () {
    try {
      setSentinel();
      column = new Integer(0);
      row = new Integer(0);
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Position


// ***** VDMTOOLS START Name=Position KEEP=NO
  public Position () throws CGException {
    vdm_init_Position();
  }
// ***** VDMTOOLS END Name=Position


// ***** VDMTOOLS START Name=Position#2|Number|Number KEEP=NO
  public Position (final Number c, final Number r) throws CGException {
    vdm_init_Position();
    column = UTIL.NumberToInt(UTIL.clone(c));
    row = UTIL.NumberToInt(UTIL.clone(r));
  }
// ***** VDMTOOLS END Name=Position#2|Number|Number

}
;
