//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-05 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\João\\Documents\\GitHub\\mfes_stratego\\VDM++\\Color.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

package VDM;

import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Color implements EvaluatePP {

// ***** VDMTOOLS START Name=name KEEP=NO
  public volatile String name = null;
// ***** VDMTOOLS END Name=name

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=ColorSentinel KEEP=NO
  class ColorSentinel extends Sentinel {

    public final int Color = 0;

    public final int nr_functions = 1;


    public ColorSentinel () throws CGException {}


    public ColorSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=ColorSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new ColorSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_Color KEEP=NO
  private void vdm_init_Color () {
    try {
      setSentinel();
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Color


// ***** VDMTOOLS START Name=Color KEEP=NO
  public Color () throws CGException {
    vdm_init_Color();
  }
// ***** VDMTOOLS END Name=Color


// ***** VDMTOOLS START Name=Color#1|String KEEP=NO
  public Color (final String n) throws CGException {
    vdm_init_Color();
    name = UTIL.ConvertToString(UTIL.clone(n));
  }
// ***** VDMTOOLS END Name=Color#1|String

}
;
