//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-05 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\João\\Documents\\GitHub\\mfes_stratego\\VDM++\\Play.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

package VDM;

import java.util.Map;
import java.util.HashMap;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Record;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Play implements EvaluatePP {

// ***** VDMTOOLS START Name=game KEEP=NO
  private volatile Game game = null;
// ***** VDMTOOLS END Name=game

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=PlaySentinel KEEP=NO
  class PlaySentinel extends Sentinel {

    public final int play = 0;

    public final int swap = 1;

    public final int getTurn = 2;

    public final int getBoard = 3;

    public final int getEnded = 4;

    public final int getWinner = 5;

    public final int validPlay = 6;

    public final int validSwap = 7;

    public final int initializeBoard = 8;

    public final int nr_functions = 9;


    public PlaySentinel () throws CGException {}


    public PlaySentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=PlaySentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new PlaySentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_Play KEEP=NO
  private void vdm_init_Play () {
    try {
      setSentinel();
      game = new Game();
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Play


// ***** VDMTOOLS START Name=Play KEEP=NO
  public Play () throws CGException {
    vdm_init_Play();
  }
// ***** VDMTOOLS END Name=Play


// ***** VDMTOOLS START Name=initializeBoard KEEP=NO
  public void initializeBoard () throws CGException {
    sentinel.entering(((PlaySentinel)sentinel).initializeBoard);
    try {
      game.addPiece(new Game.Position(new Integer(0), new Integer(0)), new Piece(new Rank(new String("two")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(1), new Integer(0)), new Piece(new Rank(new String("three")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(2), new Integer(0)), new Piece(new Rank(new String("eight")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(3), new Integer(0)), new Piece(new Rank(new String("two")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(4), new Integer(0)), new Piece(new Rank(new String("three")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(5), new Integer(0)), new Piece(new Rank(new String("two")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(6), new Integer(0)), new Piece(new Rank(new String("four")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(7), new Integer(0)), new Piece(new Rank(new String("two")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(8), new Integer(0)), new Piece(new Rank(new String("ten")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(9), new Integer(0)), new Piece(new Rank(new String("flag")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(0), new Integer(1)), new Piece(new Rank(new String("three")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(1), new Integer(1)), new Piece(new Rank(new String("two")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(2), new Integer(1)), new Piece(new Rank(new String("six")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(3), new Integer(1)), new Piece(new Rank(new String("three")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(4), new Integer(1)), new Piece(new Rank(new String("four")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(5), new Integer(1)), new Piece(new Rank(new String("five")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(6), new Integer(1)), new Piece(new Rank(new String("three")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(7), new Integer(1)), new Piece(new Rank(new String("six")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(8), new Integer(1)), new Piece(new Rank(new String("four")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(9), new Integer(1)), new Piece(new Rank(new String("four")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(0), new Integer(2)), new Piece(new Rank(new String("bomb")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(1), new Integer(2)), new Piece(new Rank(new String("bomb")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(2), new Integer(2)), new Piece(new Rank(new String("spy")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(3), new Integer(2)), new Piece(new Rank(new String("seven")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(4), new Integer(2)), new Piece(new Rank(new String("bomb")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(5), new Integer(2)), new Piece(new Rank(new String("bomb")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(6), new Integer(2)), new Piece(new Rank(new String("seven")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(7), new Integer(2)), new Piece(new Rank(new String("five")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(8), new Integer(2)), new Piece(new Rank(new String("bomb")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(9), new Integer(2)), new Piece(new Rank(new String("bomb")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(0), new Integer(3)), new Piece(new Rank(new String("six")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(1), new Integer(3)), new Piece(new Rank(new String("two")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(2), new Integer(3)), new Piece(new Rank(new String("five")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(3), new Integer(3)), new Piece(new Rank(new String("eight")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(4), new Integer(3)), new Piece(new Rank(new String("two")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(5), new Integer(3)), new Piece(new Rank(new String("two")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(6), new Integer(3)), new Piece(new Rank(new String("nine")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(7), new Integer(3)), new Piece(new Rank(new String("six")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(8), new Integer(3)), new Piece(new Rank(new String("five")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(9), new Integer(3)), new Piece(new Rank(new String("seven")), new Color(new String("red"))));
      game.addPiece(new Game.Position(new Integer(9), new Integer(9)), new Piece(new Rank(new String("two")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(8), new Integer(9)), new Piece(new Rank(new String("three")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(7), new Integer(9)), new Piece(new Rank(new String("eight")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(6), new Integer(9)), new Piece(new Rank(new String("two")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(5), new Integer(9)), new Piece(new Rank(new String("three")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(4), new Integer(9)), new Piece(new Rank(new String("two")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(3), new Integer(9)), new Piece(new Rank(new String("four")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(2), new Integer(9)), new Piece(new Rank(new String("two")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(1), new Integer(9)), new Piece(new Rank(new String("ten")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(0), new Integer(9)), new Piece(new Rank(new String("flag")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(9), new Integer(8)), new Piece(new Rank(new String("three")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(8), new Integer(8)), new Piece(new Rank(new String("two")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(7), new Integer(8)), new Piece(new Rank(new String("six")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(6), new Integer(8)), new Piece(new Rank(new String("three")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(5), new Integer(8)), new Piece(new Rank(new String("four")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(4), new Integer(8)), new Piece(new Rank(new String("five")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(3), new Integer(8)), new Piece(new Rank(new String("three")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(2), new Integer(8)), new Piece(new Rank(new String("six")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(1), new Integer(8)), new Piece(new Rank(new String("four")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(0), new Integer(8)), new Piece(new Rank(new String("four")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(9), new Integer(7)), new Piece(new Rank(new String("bomb")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(8), new Integer(7)), new Piece(new Rank(new String("bomb")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(7), new Integer(7)), new Piece(new Rank(new String("spy")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(6), new Integer(7)), new Piece(new Rank(new String("seven")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(5), new Integer(7)), new Piece(new Rank(new String("bomb")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(4), new Integer(7)), new Piece(new Rank(new String("bomb")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(3), new Integer(7)), new Piece(new Rank(new String("seven")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(2), new Integer(7)), new Piece(new Rank(new String("five")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(1), new Integer(7)), new Piece(new Rank(new String("bomb")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(0), new Integer(7)), new Piece(new Rank(new String("bomb")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(9), new Integer(6)), new Piece(new Rank(new String("six")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(8), new Integer(6)), new Piece(new Rank(new String("two")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(7), new Integer(6)), new Piece(new Rank(new String("five")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(6), new Integer(6)), new Piece(new Rank(new String("eight")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(5), new Integer(6)), new Piece(new Rank(new String("two")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(4), new Integer(6)), new Piece(new Rank(new String("two")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(3), new Integer(6)), new Piece(new Rank(new String("nine")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(2), new Integer(6)), new Piece(new Rank(new String("six")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(1), new Integer(6)), new Piece(new Rank(new String("five")), new Color(new String("blue"))));
      game.addPiece(new Game.Position(new Integer(0), new Integer(6)), new Piece(new Rank(new String("seven")), new Color(new String("blue"))));
    }
    finally {
      sentinel.leaving(((PlaySentinel)sentinel).initializeBoard);
    }
  }
// ***** VDMTOOLS END Name=initializeBoard


// ***** VDMTOOLS START Name=validSwap#4|Number|Number|Number|Number KEEP=NO
  public Boolean validSwap (final Number fc, final Number fr, final Number tc, final Number tr) throws CGException {
    sentinel.entering(((PlaySentinel)sentinel).validSwap);
    try {
      return game.validSwapPositions(fc, fr, tc, tr);
    }
    finally {
      sentinel.leaving(((PlaySentinel)sentinel).validSwap);
    }
  }
// ***** VDMTOOLS END Name=validSwap#4|Number|Number|Number|Number


// ***** VDMTOOLS START Name=swap#4|Number|Number|Number|Number KEEP=NO
  public void swap (final Number fc, final Number fr, final Number tc, final Number tr) throws CGException {
    sentinel.entering(((PlaySentinel)sentinel).swap);
    try {
      game.swapPositions(fc, fr, tc, tr);
    }
    finally {
      sentinel.leaving(((PlaySentinel)sentinel).swap);
    }
  }
// ***** VDMTOOLS END Name=swap#4|Number|Number|Number|Number


// ***** VDMTOOLS START Name=validPlay#4|Number|Number|Number|Number KEEP=NO
  public Boolean validPlay (final Number fc, final Number fr, final Number tc, final Number tr) throws CGException {
    sentinel.entering(((PlaySentinel)sentinel).validPlay);
    try {
      return game.validMove(fc, fr, tc, tr);
    }
    finally {
      sentinel.leaving(((PlaySentinel)sentinel).validPlay);
    }
  }
// ***** VDMTOOLS END Name=validPlay#4|Number|Number|Number|Number


// ***** VDMTOOLS START Name=play#4|Number|Number|Number|Number KEEP=NO
  public void play (final Number fc, final Number fr, final Number tc, final Number tr) throws CGException {
    sentinel.entering(((PlaySentinel)sentinel).play);
    try {
      game.move(fc, fr, tc, tr);
    }
    finally {
      sentinel.leaving(((PlaySentinel)sentinel).play);
    }
  }
// ***** VDMTOOLS END Name=play#4|Number|Number|Number|Number


// ***** VDMTOOLS START Name=getBoard KEEP=NO
  public Map getBoard () throws CGException {
    sentinel.entering(((PlaySentinel)sentinel).getBoard);
    try {
      return (game.board);
    }
    finally {
      sentinel.leaving(((PlaySentinel)sentinel).getBoard);
    }
  }
// ***** VDMTOOLS END Name=getBoard


// ***** VDMTOOLS START Name=getTurn KEEP=NO
  public String getTurn () throws CGException {
    sentinel.entering(((PlaySentinel)sentinel).getTurn);
    try {
      return (game.turn);
    }
    finally {
      sentinel.leaving(((PlaySentinel)sentinel).getTurn);
    }
  }
// ***** VDMTOOLS END Name=getTurn


// ***** VDMTOOLS START Name=getEnded KEEP=NO
  public Boolean getEnded () throws CGException {
    sentinel.entering(((PlaySentinel)sentinel).getEnded);
    try {
      return game.gameEnded();
    }
    finally {
      sentinel.leaving(((PlaySentinel)sentinel).getEnded);
    }
  }
// ***** VDMTOOLS END Name=getEnded


// ***** VDMTOOLS START Name=getWinner KEEP=NO
  public String getWinner () throws CGException {
    sentinel.entering(((PlaySentinel)sentinel).getWinner);
    try {
      return game.getWinner();
    }
    finally {
      sentinel.leaving(((PlaySentinel)sentinel).getWinner);
    }
  }
// ***** VDMTOOLS END Name=getWinner

}
;
