//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-05 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\João\\Documents\\GitHub\\mfes_stratego\\VDM++\\Rank.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

package VDM;

import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Rank implements EvaluatePP {

// ***** VDMTOOLS START Name=name KEEP=NO
  public volatile String name = null;
// ***** VDMTOOLS END Name=name

// ***** VDMTOOLS START Name=avaiability KEEP=NO
  public volatile Number avaiability = null;
// ***** VDMTOOLS END Name=avaiability

// ***** VDMTOOLS START Name=movement KEEP=NO
  public volatile Number movement = null;
// ***** VDMTOOLS END Name=movement

// ***** VDMTOOLS START Name=number KEEP=NO
  public volatile Number number = null;
// ***** VDMTOOLS END Name=number

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=RankSentinel KEEP=NO
  class RankSentinel extends Sentinel {

    public final int Rank = 0;

    public final int nr_functions = 1;


    public RankSentinel () throws CGException {}


    public RankSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=RankSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new RankSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_Rank KEEP=NO
  private void vdm_init_Rank () {
    try {
      setSentinel();
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Rank


// ***** VDMTOOLS START Name=Rank KEEP=NO
  public Rank () throws CGException {
    vdm_init_Rank();
  }
// ***** VDMTOOLS END Name=Rank

  
// ***** VDMTOOLS START Name=Rank#1|String KEEP=NO
  public Rank (final String n) throws CGException {
    vdm_init_Rank();
    name = UTIL.ConvertToString(UTIL.clone(n));
    boolean succ_3 = false;
    {
      /* "water" */
      succ_3 = (UTIL.equals(name, new String("water")));
      if (succ_3) {
        avaiability = new Integer(8);
      }
    }
    if (!succ_3) {
      /* "null" */
      succ_3 = (UTIL.equals(name, new String("null")));
      if (succ_3) {
        avaiability = new Integer(100);
      }
    }
    if (!succ_3) {
      /* "ten" */
      succ_3 = (UTIL.equals(name, new String("ten")));
      if (!succ_3) {
        /* "nine" */
        succ_3 = (UTIL.equals(name, new String("nine")));
      }
      if (!succ_3) {
        /* "spy" */
        succ_3 = (UTIL.equals(name, new String("spy")));
      }
      if (!succ_3) {
        /* "flag" */
        succ_3 = (UTIL.equals(name, new String("flag")));
      }
      if (succ_3) {
        avaiability = new Integer(1);
      }
    }
    if (!succ_3) {
      /* "eight" */
      succ_3 = (UTIL.equals(name, new String("eight")));
      if (succ_3) {
        avaiability = new Integer(2);
      }
    }
    if (!succ_3) {
      /* "seven" */
      succ_3 = (UTIL.equals(name, new String("seven")));
      if (succ_3) {
        avaiability = new Integer(3);
      }
    }
    if (!succ_3) {
      /* "six" */
      succ_3 = (UTIL.equals(name, new String("six")));
      if (!succ_3) {
        /* "five" */
        succ_3 = (UTIL.equals(name, new String("five")));
      }
      if (!succ_3) {
        /* "four" */
        succ_3 = (UTIL.equals(name, new String("four")));
      }
      if (succ_3) {
        avaiability = new Integer(4);
      }
    }
    if (!succ_3) {
      /* "three" */
      succ_3 = (UTIL.equals(name, new String("three")));
      if (succ_3) {
        avaiability = new Integer(5);
      }
    }
    if (!succ_3) {
      /* "bomb" */
      succ_3 = (UTIL.equals(name, new String("bomb")));
      if (succ_3) {
        avaiability = new Integer(6);
      }
    }
    if (!succ_3) {
      /* "two" */
      succ_3 = (UTIL.equals(name, new String("two")));
      if (succ_3) {
        avaiability = new Integer(8);
      }
    }
    boolean succ_29 = false;
    {
      /* "water" */
      succ_29 = (UTIL.equals(name, new String("water")));
      if (!succ_29) {
        /* "bomb" */
        succ_29 = (UTIL.equals(name, new String("bomb")));
      }
      if (!succ_29) {
        /* "flag" */
        succ_29 = (UTIL.equals(name, new String("flag")));
      }
      if (!succ_29) {
        /* "null" */
        succ_29 = (UTIL.equals(name, new String("null")));
      }
      if (succ_29) {
        movement = new Integer(0);
      }
    }
    if (!succ_29) {
      /* "spy" */
      succ_29 = (UTIL.equals(name, new String("spy")));
      if (succ_29) {
        movement = new Integer(9);
      }
    }
    /* others */
    if (!succ_29) {
      movement = new Integer(1);
    }
    boolean succ_40 = false;
    {
      /* "two" */
      succ_40 = (UTIL.equals(name, new String("two")));
      if (succ_40) {
        number = new Integer(2);
      }
    }
    if (!succ_40) {
      /* "three" */
      succ_40 = (UTIL.equals(name, new String("three")));
      if (succ_40) {
        number = new Integer(3);
      }
    }
    if (!succ_40) {
      /* "four" */
      succ_40 = (UTIL.equals(name, new String("four")));
      if (succ_40) {
        number = new Integer(4);
      }
    }
    if (!succ_40) {
      /* "five" */
      succ_40 = (UTIL.equals(name, new String("five")));
      if (succ_40) {
        number = new Integer(5);
      }
    }
    if (!succ_40) {
      /* "six" */
      succ_40 = (UTIL.equals(name, new String("six")));
      if (succ_40) {
        number = new Integer(6);
      }
    }
    if (!succ_40) {
      /* "seven" */
      succ_40 = (UTIL.equals(name, new String("seven")));
      if (succ_40) {
        number = new Integer(7);
      }
    }
    if (!succ_40) {
      /* "eight" */
      succ_40 = (UTIL.equals(name, new String("eight")));
      if (succ_40) {
        number = new Integer(8);
      }
    }
    if (!succ_40) {
      /* "nine" */
      succ_40 = (UTIL.equals(name, new String("nine")));
      if (succ_40) {
        number = new Integer(9);
      }
    }
    if (!succ_40) {
      /* "ten" */
      succ_40 = (UTIL.equals(name, new String("ten")));
      if (succ_40) {
        number = new Integer(10);
      }
    }
    if (!succ_40) {
      /* "spy" */
      succ_40 = (UTIL.equals(name, new String("spy")));
      if (succ_40) {
        number = new Integer(1);
      }
    }
    if (!succ_40) {
      /* "bomb" */
      succ_40 = (UTIL.equals(name, new String("bomb")));
      if (succ_40) {
        number = new Integer(0);
      }
    }
    if (!succ_40) {
      /* "flag" */
      succ_40 = (UTIL.equals(name, new String("flag")));
      if (succ_40) {
        number = new Integer(0);
      }
    }
    if (!succ_40) {
      /* "water" */
      succ_40 = (UTIL.equals(name, new String("water")));
      if (succ_40) {
        number = new Integer(0);
      }
    }
    if (!succ_40) {
      /* "null" */
      succ_40 = (UTIL.equals(name, new String("null")));
      if (succ_40) {
        number = new Integer(0);
      }
    }
    //UTIL.RunTime("The operation did not return a value");
    //return new Rank();
  }
// ***** VDMTOOLS END Name=Rank#1|String

}
;
